[package]
name = "cam-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
# aligned = "=0.4.3"
# base64 = { version = "=0.23.1", default-features = false, features = ["alloc"] }
embassy-executor = "=0.10.0"
embedded-hal = "=1.0.0"
esp-backtrace = { version = "=0.20.0", features = ["panic-handler", "println"] }
esp-bootloader-esp-idf = "=0.6.0"
esp-hal = { version = "=1.2.0", features = ["log-04", "unstable"] }
esp-println = { version = "=0.18.0", features = ["log-04"] }
esp-rtos = { version = "=0.4.0", features = ["embassy"] }
log = "=0.4.34"

[features]
default = ["esp32s3"]

esp32 = [
    "esp-backtrace/esp32",
    "esp-bootloader-esp-idf/esp32",
    "esp-hal/esp32",
    "esp-println/esp32",
]
esp32s3 = [
    "esp-backtrace/esp32s3",
    "esp-bootloader-esp-idf/esp32s3",
    "esp-hal/esp32s3",
    "esp-println/esp32s3",
    "esp-rtos/esp32s3",
]

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.dev.package."*"]
opt-level = 1

[profile.release]
opt-level = 3
lto = "thin"
panic = "abort"
codegen-units = 1
debug = false

[patch.crates-io]
esp-hal = { path = "/home/iurii/$/projects/esp-hal/esp-hal" }
esp-rom-sys = { path = "/home/iurii/$/projects/esp-hal/esp-rom-sys" }